<?php include 'top.php'; top("Home","img/DSC04859.JPG") ?>
<h1>h1 Header</h1>
<p>Venturing is a co-ed scouting program for youth ages 14-21. The program is a branch of the organization known as Boy Scouts of America, or BSA. Other branches include the Boy Scouts, Sea scouts, Cub Scouts, and Varsity Scouts. The program is designed to be youth led, and teaches valuable skills, such as survival skills, leadership skills, and teamwork. Activities include high adventure camps such as Philmont, Sea base, and Summit Bechtel Reserve. We also go backpacking, kayaking and canoeing, among other activities. For more information on Venturing, Scouting, or these camps, please check our <a href="index.php">FAQ page.</a></p>
            
<h2>h2 Header</h2>
<p>Venturing is a co-ed scouting program for youth ages 14-21. The program is a branch of the organization known as Boy Scouts of America, or BSA. Other branches include the Boy Scouts, Sea scouts, Cub Scouts, and Varsity Scouts. The program is designed to be youth led, and teaches valuable skills, such as survival skills, leadership skills, and teamwork. Activities include high adventure camps such as Philmont, Sea base, and Summit Bechtel Reserve. We also go backpacking, kayaking and canoeing, among other activities. For more information on Venturing, Scouting, or these camps, please check our FAQ page.</p>
            
<h3>h3 Header</h3>
<p>Venturing is a co-ed scouting program for youth ages 14-21. The program is a branch of the organization known as Boy Scouts of America, or BSA. Other branches include the Boy Scouts, Sea scouts, Cub Scouts, and Varsity Scouts. The program is designed to be youth led, and teaches valuable skills, such as survival skills, leadership skills, and teamwork. Activities include high adventure camps such as Philmont, Sea base, and Summit Bechtel Reserve. We also go backpacking, kayaking and canoeing, among other activities. For more information on Venturing, Scouting, or these camps, please check our FAQ page.</p>
<?php include 'bottom.php'; ?>